services:
  pg:
    image: postgres:17.2-alpine3.21
    env_file:
      - local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_users_volume:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_users_volume:
  redis_data: